// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID              uuid.UUID   `json:"id"`
	ProjectID       uuid.UUID   `json:"projectId"`
	SenderID        uuid.UUID   `json:"senderId"`
	Content         string      `json:"content"`
	MessageType     string      `json:"messageType"`
	ParentMessageID pgtype.UUID `json:"parentMessageId"`
	CreatedAt       time.Time   `json:"createdAt"`
	UpdatedAt       time.Time   `json:"updatedAt"`
}

// Temporary storage for OAuth state tokens (CSRF protection)
type OauthState struct {
	ID uuid.UUID `json:"id"`
	// Random CSRF token for OAuth flow
	StateToken string `json:"stateToken"`
	// User preference for persistent login
	RememberMe bool `json:"rememberMe"`
	// Frontend URL to redirect after successful auth
	RedirectUrl *string   `json:"redirectUrl"`
	CreatedAt   time.Time `json:"createdAt"`
	// State tokens expire after 10 minutes
	ExpiresAt time.Time `json:"expiresAt"`
}

type PasswordReset struct {
	ID         int32     `json:"id"`
	UserID     uuid.UUID `json:"userId"`
	ResetToken string    `json:"resetToken"`
	ExpiresAt  time.Time `json:"expiresAt"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Project struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"ownerId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ProjectInvite struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"projectId"`
	CreatedBy   uuid.UUID `json:"createdBy"`
	InviteToken string    `json:"inviteToken"`
	ExpiresAt   time.Time `json:"expiresAt"`
	MaxUses     *int32    `json:"maxUses"`
	UsedCount   int32     `json:"usedCount"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"projectId"`
	UserID    uuid.UUID `json:"userId"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joinedAt"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedAt time.Time `json:"createdAt"`
	// True for persistent login (Remember Me), false for session-only
	IsPersistent bool `json:"isPersistent"`
	// Google OAuth refresh token for re-authentication
	GoogleRefreshToken *string `json:"googleRefreshToken"`
	// Google OAuth access token (cached for API calls)
	GoogleAccessToken *string `json:"googleAccessToken"`
	// Expiration time for Google access token
	GoogleTokenExpiry pgtype.Timestamptz `json:"googleTokenExpiry"`
}

type Sprint struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"projectId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	StartDate   time.Time `json:"startDate"`
	EndDate     time.Time `json:"endDate"`
	IsCompleted bool      `json:"isCompleted"`
	IsStarted   bool      `json:"isStarted"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Task struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   uuid.UUID   `json:"projectId"`
	SprintID    pgtype.UUID `json:"sprintId"`
	AssigneeID  pgtype.UUID `json:"assigneeId"`
	Title       string      `json:"title"`
	Description *string     `json:"description"`
	Status      int32       `json:"status"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	PasswordH *string   `json:"passwordH"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Active    bool      `json:"active"`
	AvatarUrl *string   `json:"avatarUrl"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	// Authentication method: local (username/password) or google (OAuth)
	AuthProvider *string `json:"authProvider"`
	// Google unique user identifier (sub claim from Google)
	GoogleID *string `json:"googleId"`
	// User profile picture URL from Google
	ProfilePictureUrl *string `json:"profilePictureUrl"`
}
