version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devhive
      POSTGRES_USER: devhive
      POSTGRES_PASSWORD: devhive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devhive -d devhive"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://devhive:devhive@postgres:5432/devhive?sslmode=disable
      JWT_SIGNING_KEY: your-super-secret-jwt-key-change-in-production
      JWT_ISSUER: https://api.devhive.it.com
      JWT_AUDIENCE: devhive-clients
      CORS_ORIGINS: http://localhost:3000,https://d35scdhidypl44.cloudfront.net,https://devhive.it.com
      CORS_ALLOW_CREDENTIALS: true
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devhive.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: