app = "devhive-go-backend"
primary_region = "iad"

[env]
  PORT = "8080"
  GIN_MODE = "release"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  [http_service.headers]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"

[[domains]]
  name = "go.devhive.it.com"

[deploy]
  strategy = "immediate"

[metrics]
  port = 9091
  path = "/metrics"
