# Trivy security scanner configuration
format: table
severity: CRITICAL,HIGH,MEDIUM
exit-code: 1
ignore-unfixed: false
ignorefile: .trivyignore
timeout: 5m
quiet: false
no-progress: false

# Skip scanning for development dependencies
skip-dirs:
  - vendor/
  - node_modules/
  - .git/

# Skip certain vulnerability types that are false positives
skip-files:
  - "**/*.test.go"
  - "**/*_test.go"

# Custom vulnerability filters
vuln-type: os,library