name: Deploy (Production)
on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
      - 'cmd/**'
      - 'internal/**'
      - 'go.*'
      - 'fly.toml'
concurrency:
  group: deploy-prod
  cancel-in-progress: true
permissions:
  contents: read
  packages: write
jobs:
  build:
    uses: ./.github/workflows/02-build-image.yml
    with:
      push: true
      platforms: linux/amd64

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1.8.0
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --strategy immediate
      - name: Verify health
        run: |
          flyctl checks list --json | jq -e '.[] | select(.Status!="passing")' && exit 1 || echo OK
